### ISSUE TITLE
Confusing Theme Documentation

### ISSUE THREAD

**Issue by knurdtech** [ruhoh/ruhoh.com#10]
Just a little wording issue unless I'm reading incorrectly.

On https://github.com/ruhoh/ruhoh.com/blob/master/docs/2/index.md under "Add Theme" (#toc_3) it says "Finally, every theme-level file can be overwritten by providing the same file within your site directory "ruhoh-site".

My understanding from the documentation elsewhere is theme-level being the highest level...not the other way around.

**Comment by nacnudus** [comment]
This is my experience, too.  To reproduce the problem, follow the get-started instructions here: http://ruhoh.com/docs/2/
- Preview your site on localhost and create the index.md file as suggested.
- Install the suggested theme-bootstrap-2
- Preview your site again.  The default index.html page in the theme-bootstrap-2/_root directory is overriding the index.md page you created in the earlier step.

**Comment by knurdtech** [comment]
Assuming this project is abandoned.
