### ISSUE TITLE
http://ruhoh.com does't load right now

### ISSUE THREAD

**Issue by kablamo** [ruhoh/ruhoh.com#3]
You need to use a CNAME record instead of framing.

ps ruhoh looks awesome!

**Comment by plusjade** [comment]
@kablamo thanks! I've just pushed an update and looks like it's working again! Please verify.

https://github.com/ruhoh/ruhoh.com/commit/14ae1f7e8a1da476a58ab07cf725a33b3aedb927

**Comment by kablamo** [comment]
Hmm that seems to be working even less now.  I see a parked godaddy page.

**Comment by plusjade** [comment]
I can't reproduce that. I've asked some other people in different areas to load it up and seems to be working fine.

**Comment by kablamo** [comment]
Oh my bad.  i was looking at ruhruh.com.   You are right the site is working now.  Thanks!
